version: '3.7'
services:
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  frontend:
      build: ./frontend
      volumes:
        - ./frontend:/app/frontend
      ports:
        - "3001:80"
      depends_on:
        - backend
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "54322:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  